src/components/Example.tsx
A simple `a` wrapper around the `IconButton` that when clicked opens the sample in a new tab
=> clicking on "Open in Fullscreen" opens in new tab

package.json, src/components/CodeSample.tsx
Added a simple Copy button in the `CodeSample.tsx` file.
Here's how it looks like:
https://user-images.githubusercontent.com/5396211/103403565-e2d4dd00-4b50-11eb-8163-639637f25d07.mov
=> added Copy to Clipboard functionality

src/components/Header.tsx
I felt it's intuitive. I found myself clicking a few times on it and expected to navigate to the root page.
=> made title clickable and leading to /

src/components/Example.tsx, src/components/ResizableFrame.tsx, src/utils/getExampleUrl.ts
=> fix(firefox): set example iframe url in client only

src/components/HeaderBar.tsx, src/components/Navigation.tsx, src/components/SEO.tsx, src/constants.ts, src/pages/[...slug].tsx, src/pages/_app.tsx, src/pages/index.tsx
Added SEO component with ordinary, Facebook and Twitter SEO meta tags. Could be improved for every template individually, but this works for now.
=> Feature: added SEO meta tags in separate SEO component

src/data/index.tsx, src/pages/templates/forms/authentication/joinOurTeam.tsx
=> feature(template): add new join our team form template

src/pages/templates/components/social-media-buttons/All.tsx, src/pages/templates/components/social-media-buttons/Facebook.tsx, src/pages/templates/components/social-media-buttons/Google.tsx, src/pages/templates/components/social-media-buttons/LinkedIn.tsx, src/pages/templates/components/social-media-buttons/Messenger.tsx, yarn.lock
- Updated the paddings of the buttons
=> minor: Updated the paddings of the buttons

package.json, src/data/index.tsx, src/data/templates/statistics.ts, src/pages/templates/page-sections/statistics/basicStatistics.tsx, src/pages/templates/page-sections/statistics/iconStatistics.tsx, src/pages/templates/page-sections/testimonials/gridBlurredBackdrop.tsx, yarn.lock
Don't really know much about contributing so I thought I would try. I hope I haven't messed something up!
=> feat - adding statistics page sections

src/data/templates/testimonials.ts, src/pages/templates/page-sections/testimonials/gridBlurredBackdrop.tsx
Saw that issue #40 hadn't been answered since Feb so had a stab. Not sure about the dark mode version
=> feat Added testimonial - gridblurredbackdrop. solve for #40

src/data/components/cards.ts, src/pages/templates/components/cards/productAddToCart.tsx
=> feat: Adding Card - Product card with add to cart button

src/pages/templates/navigation/navbar/withSubnavigation.tsx
=> fix: Move hook out of map function DesktopNav

src/data/index.tsx, src/data/templates/sidebar.ts, src/pages/templates/navigation/sidebar/sidebarWithHeader.tsx, src/pages/templates/navigation/sidebar/simpleSidebar.tsx
- Added a new subsection in Navigation called Sidebar
- Made a sidebar component - SImple SIdebar
=> feat: added new sidebar component - simple sidebar

src/pages/templates/navigation/navbar/simple.tsx, src/pages/templates/navigation/navbar/withAction.tsx
=> 🐛 Fix focus ring width

package.json, src/components/Header/index.tsx, src/components/ResizableFrame.tsx, src/components/motion/MotionBox.tsx, src/pages/_app.tsx, yarn.lock
- Feature: Integrated HyperTheme Editor Free version in the top right corner of the Header.
- Chore: upgraded ChakraUI (also emotion and framer-motion).
We'll update the NPM module, so probably we will make other PRs in order to upgrade the theme editor.
I remember that this is a free version with limited functionalities.
=> feat: HyperTheme Editor Integration

package.json, yarn.lock
Updated HyperTheme Editor to v0.0.31!
Changelog:
- Edit palette feature!
- fix horizontal scrolling of the editor on mobile devices.
- fix a bug when setting css vars.
=> chore: update HyperTheme Editor

package.json, src/components/Header/CTThemeEditor.tsx, src/components/Header/index.tsx, src/components/ResizableFrame.tsx, yarn.lock
Upgraded HyperTheme Editor to v0.1.2.
Starting from this release HyperTheme is licensed under the MIT license.
=> refactor: upgraded HyperTheme to v0.1

src/data/templates/features.ts, src/pages/templates/page-sections/features/gridListWithCTA.tsx
Hi, this is my first ever contributions to a open source, let me know if I have done it correct,
Thank you
=> Feat: add new features page section with call to action

src/data/components/cards.ts, src/pages/templates/components/cards/socialUserProfileHorizontal.tsx
Added social user profile horizontal card.
=> Feature: Card Horizontal Component

src/pages/templates/page-sections/testimonials/gridBlurredBackdrop.tsx
Fixes a typo in gridBlurredBackdrop testimonial template
=> Fix typo in testimonial templates

src/data/templates/pricing.ts, src/pages/templates/page-sections/pricing/threeTierPricingHorizontal.tsx
New component in category Pricing
=> [Feature] Add new component pricing

src/data/components/buttons.ts, src/pages/templates/components/buttons/clickMe.tsx, src/pages/templates/components/buttons/followButtonWithShadow.tsx
Based on the [issue](https://github.com/hauptrolle/chakra-templates/issues/159) #159 opened, I extracted two button from card components and add a little background colour changes when user click on "Click Me" button.
=> feat(button): add button extracted from card components

src/components/HomepageSections/Hero.tsx, src/data/components/buttons.ts, src/data/components/socialMediaButtons.ts, src/data/index.tsx, src/pages/templates/components/buttons/buttonTabbedPopover.tsx, src/pages/templates/components/buttons/colorModeToggle.tsx, src/pages/templates/components/buttons/secondaryOptions.tsx
Currently, the homepage Hero has the feature as - "Written in Typescript", whereas it should be "Written in TypeScript" (ref: https://www.typescriptlang.org/).
=> fix(typo): TypeScript in Homepage Hero

src/pages/templates/forms/authentication/joinOurTeam.tsx
=> fix icon deforming when scaling

next-env.d.ts, src/data/templates/authentication.ts, src/pages/templates/forms/authentication/verifyEmail.tsx
Added a verify email card component.
=> feat: add verify email card component

src/pages/templates/navigation/navbar/withSubnavigation.tsx
fixed the error 
please let me know if any error comes up
=> fix: fixed issue on button in With Sub-Navigation & CTA

src/data/components/accordion.ts, src/data/index.tsx, src/pages/templates/components/accordion/simpleAccordion.tsx
I created a new '**Accordion**' category within the '**Components**' section and added a simple accordion to it.
=> feat: simple accordion
